---
- hosts: localhost
  vars:
    githubuser: "paysancorrezien"

  tasks:
    - name: Install required packages
      become: yes
      apt:
        pkg:
        - curl
        - git
        - python3
        - python3-pip
        - python3-setuptools
        - xclip
        - zathura
        - wget
        - autorandr
        - jq
        - flameshot
        - fzf
        - zoxide
        - bat
        - ripgrep
        - tmux
        - fd-find
        - exa
        - neofetch
        - zsh
        - unzip
        update_cache: yes

    - name: Install python packages
      command:
        cmd: pip3 install -U pip

    - name: Change shell to zsh
      become: yes
      shell: chsh -s /usr/bin/zsh "{{ ansible_env.USER }}" 
      args:
        executable: /bin/bash

    - name: Install Zap for Zsh
      become: yes
      shell: 
        cmd: zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/release-v1/install.zsh)
      args:
        executable: /bin/bash

    - name: Install chezmoi
      become: yes
      shell:
        cmd: |
          sh -c "$(curl -fsLS git.io/chezmoi)"
          mv ./bin/chezmoi /usr/local/bin/

    - name: Clone the dotfiles repository using HTTPS
      git:
        repo: 'https://github.com/{{ githubuser }}/dotfiles.git'
        dest: "{{ ansible_env.HOME }}/.local/share/chezmoi"
        version: "main"
        force: yes

    - name: Ensure chezmoi.toml exists with default values
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config/chezmoi/chezmoi.toml"
        content: |
          [data]
          git = { name = "Default Name", email = "default@email.com", gpg = "DefaultKey" }
        force: no

    - name: Initialize chezmoi
      command: chezmoi init --apply {{ githubuser }}

    - name: Update chezmoi
      command: chezmoi update

    - name: Install NVM
      become: yes
      shell:
        cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        environment:
          HOME: "{{ ansible_env.HOME }}"
          USER: "{{ ansible_env.USER }}"
          SHELL: "/bin/bash"

    - name: Wait for NVM to install
      wait_for:
        path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
        state: present

    - name: Install Node.js using NVM
      become: yes
      shell:
        cmd: |
          export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install node
          nvm use node
        environment:
          HOME: "{{ ansible_env.HOME }}"
          USER: "{{ ansible_env.USER }}"
          SHELL: "/bin/bash"

    - name: Install Fira Code Nerd Font
      become: yes
      shell:
        cmd:```yaml
          fonts_dir="${HOME}/.local/share/fonts"
          if [ ! -d "${fonts_dir}" ]; then
              mkdir -p "${fonts_dir}"
          fi

          version=6.2
          zip=FiraCode_${version}.zip
          url=https://github.com/ryanoasis/nerd-fonts/releases/download/v${version}/FiraCode.zip
          curl --fail --location --show-error ${url} --output ${zip}
          unzip -o -q -d ${fonts_dir} ${zip}
          rm ${zip}

          fc-cache -f
        environment:
          HOME: "{{ ansible_env.HOME }}"
          USER: "{{ ansible_env.USER }}"
          SHELL: "/bin/bash"
