---
- hosts: localhost
  vars:
    githubuser: "paysancorrezien"
  vars_prompt:
    - name: "githubtoken"
      prompt: "Enter your GitHub personal access token"
      private: yes
  tasks:
    - name: Install required packages
      become: yes
      shell: |
        apt-get update
        apt-get install -y curl git python3 python3-pip python3-setuptools xclip zathura wget autorandr jq flameshot fzf zoxide bat ripgrep tmux fd-find exa neofetch

    - name: Increase Git buffer size
      shell: |
        git config --global http.postBuffer 524288000

    - name: Clone the dotfiles repository
      git:
        repo: "https://{{ githubuser }}:{{ githubtoken }}@github.com/paysancorrezien/dotfiles.git"
        dest: "~/dotfiles"
        version: main
        force: yes

    - name: Ensure remote URL does not contain credentials
      git_config:
        name: remote.origin.url
        value: "https://github.com/paysancorrezien/dotfiles.git"
        scope: local
        repo: "~/dotfiles"

    - name: Install python packages
      become: yes
      pip:
        name:
        - pip
        - chezmoi
        state: latest
        executable: pip3

    - name: Initialize chezmoi
      command: chezmoi init --apply {{ githubuser }}

    - name: Update chezmoi
      command: chezmoi update

    - name: Install NVM
      become: yes
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install Node.js
      become: yes
      shell: |
        . "{{ ansible_env.HOME }}/.nvm/nvm.sh"
        nvm install node
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node"

    - name: Install Zap for Zsh
      become: yes
      shell: |
        bash <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/bin/install)

    - name: Change shell to zsh
      become: yes
      user:
        name: "{{ ansible_env.USER }}"
        shell: /usr/bin/zsh

    - name: Allow ansible user to execute sudo without password
      become: yes
      lineinfile:
        dest: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
