---
- hosts: localhost
  become: yes
  vars:
    githubuser: "paysancorrezien"
  vars_prompt:
    - name: "githubtoken"
      prompt: "GitHub Token"
      private: yes

  tasks:
    - name: Install required packages
      apt:
        pkg:
        - curl
        - git
        - python3
        - python3-pip
        - python3-setuptools
        - xclip
        - zathura
        - wget
        - autorandr
        - jq
        - flameshot
        - fzf
        - zoxide
        - bat
        - ripgrep
        - tmux
        - fd-find
        - exa
        - neofetch
        update_cache: yes

    - name: Increase Git buffer size
      git_config:
        name: http.postBuffer
        value: 524288000
        scope: global

    - name: Install python packages
      command:
        cmd: pip3 install -U pip

    - name: Install chezmoi
      shell:
        cmd: sh -c "$(curl -fsLS get.chezmoi.io) -- -b /usr/local/bin"

    - name: Clone the dotfiles repository
      git:
        repo: "https://{{ githubuser }}:{{ githubtoken }}@github.com/{{ githubuser }}/dotfiles.git"
        dest: "{{ ansible_env.HOME }}/.local/share/chezmoi"
        version: "main"
        force: yes

    - name: Ensure remote URL does not contain credentials
      git_config:
        name: "remote.origin.url"
        value: "https://github.com/{{ githubuser }}/dotfiles.git"
        scope: "local"
        repo: "{{ ansible_env.HOME }}/.local/share/chezmoi"

    - name: Initialize chezmoi
      command: chezmoi init --apply {{ githubuser }}

    - name: Update chezmoi
      command: chezmoi update

    - name: Install NVM
      shell:
        cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

    - name: Install Node.js
      shell: 
        cmd: |
          . "{{ ansible_env.HOME }}/.nvm/nvm.sh"
          nvm install node

    - name: Install Zap for Zsh
      shell:
        cmd: bash <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/bin/install)

    - nameApologies for the cut-off, here is the remaining part of the playbook:

```yaml
      name: Change shell to zsh
      user:
        name: "{{ ansible_env.USER }}"
        shell: /usr/bin/zsh

    - name: Allow ansible user to execute sudo without password
      lineinfile:
        dest: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
