---
- hosts: localhost
  become: yes
  vars_prompt:
    - name: "githubuser"
      prompt: "GitHub Username"
      private: no

    - name: "githubtoken"
      prompt: "GitHub Token"
      private: yes

  tasks:
    - name: Install required packages
      apt:
        pkg:
        - git
        - zsh
        - curl
        - python3-pip
        update_cache: yes

    - name: Install python packages
      command:
        cmd: pip3 install -U pip

    - name: Install Zap for Zsh
      shell:
        cmd: bash <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/bin/install)

    - name: Change shell to zsh
      user:
        name: "{{ ansible_env.USER }}"
        shell: /usr/bin/zsh

    - name: Allow ansible user to execute sudo without password
      lineinfile:
        dest: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Install chezmoi
      shell:
        cmd: sh -c "$(curl -fsLS get.chezmoi.io)"

    - name: Clone the dotfiles repository
      git:
        repo: "https://{{ githubuser }}:{{ githubtoken }}@github.com/{{ githubuser }}/dotfiles.git"
        dest: "~/dotfiles"
        version: "main"
        force: yes

    - name: Ensure remote URL does not contain credentials
      git_config:
        name: "remote.origin.url"
        value: "https://github.com/{{ githubuser }}/dotfiles.git"
        scope: "local"
        repo: "~/dotfiles"
