---
- hosts: localhost
  vars:
    githubuser: "paysancorrezien"
  vars_prompt:
    - name: "githubtoken"
      prompt: "GitHub Token"
      private: yes
    - name: "ssh_passphrase"
      prompt: "Enter your SSH key passphrase"
      private: yes

  tasks:
    - name: Install required packages
      become: yes
      apt:
        pkg:
        - curl
        - git
        - python3
        - python3-pip
        - python3-setuptools
        - xclip
        - zathura
        - wget
        - autorandr
        - jq
        - flameshot
        - fzf
        - zoxide
        - bat
        - ripgrep
        - tmux
        - fd-find
        - exa
        - neofetch
        update_cache: yes

    - name: Increase Git buffer size
      git_config:
        name: http.postBuffer
        value: 524288000
        scope: global

    - name: Install python packages
      command:
        cmd: pip3 install -U pip

    - name: Install chezmoi
      become: yes
      shell:
        cmd: |
          sh -c "$(curl -fsLS get.chezmoi.io)"
          mv ./bin/chezmoi /usr/local/bin/

    - name: Generate SSH key
      become: yes
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        ssh_key_passphrase: "{{ ssh_passphrase }}"

    - name: Print the public key
      command: cat /home/{{ ansible_user }}/.ssh/id_rsa.pub
      register: public_key
      changed_when: false
      become: yes

    - debug:
        msg: "Please add the following public key to your GitHub account: {{ public_key.stdout }}"

    - name: Pause to allow user to add key to GitHub
      pause:
        prompt: "Press enter to continue after you've added the key to GitHub"

    - name: Start ssh-agent and add key
      become: yes
      shell: |
        eval "$(ssh-agent -s)"
        echo "{{ ssh_passphrase }}" | ssh-add /home/{{ ansible_user }}/.ssh/id_rsa
      args:
        executable: /bin/bash

    - name: Clone the dotfiles repository
      git:
        repo: 'git@github.com:{{ githubuser }}/dotfiles.git'
        dest: "{{ ansible_env.HOME }}/.local/share/chezmoi"
        version: "main"
        force: yes

    - name: Initialize chezmoi
      command: chezmoi init --apply {{ githubuser }}

    - name: Update chezmoi
      command: chezmoi update

    - name: Install NVM
      become: yes
      shell:
        cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

    - name: Install Node.js
      become: yes
      shell: 
        cmd: |
          . "{{ ansible_env.HOME }}/.nvm/nvm.sh"
          nvm install node

    - name: Install Zap for Zsh
      become: yes
      shell: 
        cmd: bash <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/bin/install)

    - name: Change shell to zsh
      become: yes
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh

    - name: Allow ansible user to execute sudo without password
      become: yes
      lineinfile:
        dest: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
